version: '3.8'

services:
  torlink-web:
    build: .
    image: torlink-web
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-~/torlink}
    volumes:
      - ${DOWNLOAD_DIR:-~/torlink}:/root/Downloads/torlink
    restart: always
